[package]
name = "rust-doh"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
clap = "^2"
futures-await = "^0.1"
hyper = "^0.11"
tokio-core = "^0.1"
tokio-io = "^0.1"
tokio-timer = "^0.1"
clippy = {version = ">=0", optional = true}
